# Generated by Django 6.1 on 2026-08-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
    ]
